# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "acne-assist-app"
client_id = "09247bee7a1140d3234b772f66685c73"
application_url = "https://couples-explain-queensland-instantly.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://couples-explain-queensland-instantly.trycloudflare.com/auth/callback",
  "https://couples-explain-queensland-instantly.trycloudflare.com/auth/shopify/callback",
  "https://couples-explain-queensland-instantly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5ba5983c.myshopify.com"
